appName: tic-tac
namespace: react-app

replicaCount: 1

image:
  repository: registry.local:5000/tic-tac
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30002

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"
